_target_: large_gcs.domination_checkers.sampling_containment_w_prune_s_domination_checker.ReachesCheaperLastPosSamplingContainmentWPruneS

num_samples_per_vertex: 1
should_use_candidate_sol: false
containment_condition: -1